name: Build & Type Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6.0.1
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Type Check
        run: npm run type-check || true

      - name: Build
        run: npm run build
